name: 'Build and Release for Linux'
  
on:
  workflow_dispatch:
  
jobs:
  build-windows:
    name: 'Build for Windows'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Cache Processing
        id: cache-processing-bin-win
        uses: actions/cache@v3
        env:
          cache-name: cache-processing-bin-win
        with:
          path: |
            .\processing-4.2
            ~/Documents/Processing/libraries/
          key: processing-win

      - if: ${{ steps.cache-processing-bin-win.outputs.cache-hit != 'true' }}
        name: Download Processing Binary and Sound Lib 
        shell: powershell  
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest 'https://github.com/processing/processing4/releases/download/processing-1292-4.2/processing-4.2-windows-x64.zip' `
            -OutFile processing.zip `
            -UseBasicParsing
            
          Expand-Archive processing.zip -DestinationPath .
          
          Invoke-WebRequest 'https://github.com/processing/processing-sound/releases/download/v2.3.1/sound.zip' `
            -OutFile sound.zip `
            -UseBasicParsing
            
          Expand-Archive sound.zip -DestinationPath ~/Documents/Processing/libraries/

      - name: Build with Java      
        shell: powershell  
        run: |
          .\processing-4.2\processing-java.exe --sketch="$(pwd)\card_game" --variant="windows-amd64" --output="$(pwd)\schwimmen-win64-java" --export
          Compress-Archive schwimmen-win64-java ./schwimmen-win64-java.zip
          .\processing-4.2\processing-java.exe --sketch="$(pwd)\card_game_server" --variant="windows-amd64" --output="$(pwd)\schwimmen-server-win64-java" --export               
          Compress-Archive schwimmen-server-win64-java ./schwimmen-server-win64-java.zip
              
      - name: Build w/out Java      
        shell: powershell  
        run: |         
          .\processing-4.2\processing-java.exe --sketch="$(pwd)\card_game" --variant="windows-amd64" --output="$(pwd)\schwimmen-win64" --no-java --export
          Compress-Archive schwimmen-win64 ./schwimmen-win64.zip
          .\processing-4.2\processing-java.exe --sketch="$(pwd)\card_game_server" --variant="windows-amd64" --output="$(pwd)\schwimmen-server-win64" --no-java --export               
          Compress-Archive schwimmen-server-win64 ./schwimmen-server-win64.zip
 
      - uses: actions/upload-artifact@v2
        with:
          name: win-artifact
          path: .\*.zip
 
  build-linux:
    name: 'Build for Linux'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Cache Processing
        id: cache-processing-bin-linux
        uses: actions/cache@v3
        env:
          cache-name: cache-processing-bin-linux
        with:
          path: | 
            ./processing-4.2
            ~/sketchbook/libraries/
          key: processing-linux

      - if: ${{ steps.cache-processing-bin-linux.outputs.cache-hit != 'true' }}
        name: Download Processing Binary and Sound Lib
        run: |
          wget 'https://github.com/processing/processing4/releases/download/processing-1292-4.2/processing-4.2-linux-x64.tgz'
          tar -xf 'processing-4.2-linux-x64.tgz'
          
          wget 'https://github.com/processing/processing-sound/releases/download/v2.3.1/sound.zip'
          unzip sound.zip
          mkdir -p ~/sketchbook/libraries
          mv ./sound/ ~/sketchbook/libraries
          
      - name: Build with Java
        run: |
          ./processing-4.2/processing-java --sketch="$(pwd)/card_game" --variant="linux-amd64" --output="schwimmen-linux64-java" --export
          tar -czvf schwimmen-linux64-java.tar.gz -C schwimmen-linux64-java/ .
          
          ./processing-4.2/processing-java --sketch="$(pwd)/card_game_server" --variant="linux-amd64" --output="schwimmen-server-linux64-java" --export
          tar -czvf schwimmen-server-linux64-java.tar.gz -C schwimmen-linux64-java/ .
          
          
      - name: Build w/out Java
        run: |
          ./processing-4.2/processing-java --sketch="$(pwd)/card_game" --variant="linux-amd64" --output="schwimmen-linux64" --no-java --export
          tar -czvf schwimmen-linux64.tar.gz -C schwimmen-linux64/ .
          
          ./processing-4.2/processing-java --sketch="$(pwd)/card_game_server" --variant="linux-amd64" --output="schwimmen-server-linux64" --no-java --export
          tar -czvf schwimmen-server-linux64.tar.gz -C schwimmen-linux64/ .
      
      - uses: actions/upload-artifact@v2
        with:
          name: linux-artifact
          path: ./*.tar.gz
          
  release:
    name: 'Release Artifacts'
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: actions/download-artifact@v2
        with:
          name: linux-artifact
          
      - uses: actions/download-artifact@v2
        with:
          name: win-artifact
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "New Build"
          files: |
            LICENSE
            *.tar.gz
            *.zip
    
